// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:page": {
    params: {
      "page": string;
    };
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:page" | "/home";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$page.tsx": {
    id: "routes/$page";
    page: "/:page";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
};